Updated the error message and added Install command

diff --git a/install b/install
--- a/install
+++ b/install
@@ -25,7 +25,7 @@ if [[ -t 1 ]]; then
 fi
 
 error() {
-    echo -e "${Red}error${Color_Off}:" "$@" >&2
+    echo "${Red}error${Color_Off}:" "$@" >&2
     exit 1
 }
 
@@ -204,4 +204,3 @@ info "To get started, run:"
 if [[ $refresh_command ]]; then
     info_bold "$refresh_command"
 fi
-
diff --git a/slp b/slp
--- a/slp
+++ b/slp
@@ -15,7 +15,7 @@ if [[ -t 1 ]]; then
 fi
 
 error() {
-    echo -e "${Red}error${Color_Off}:" "$@" >&2
+    echo  "${Red}error${Color_Off}:" "$@" >&2
     exit 1
 }
 
