Added an install.sh for slp command

diff --git a/slp b/slp
--- a/slp
+++ b/slp
@@ -1,7 +1,27 @@
 # This command asks for root privileges required for pmset.
 # [ "$UID" -eq 0 ] || exec sudo "$0" "$@"
 
+# Regular Colors
+Red=''
+Green=''
 
+if [[ -t 1 ]]; then
+    # Reset
+    Color_Off='\033[0m' # Text Reset
+
+    # Regular Colors
+    Red='\033[0;31m'   # Red
+    Green='\033[0;32m' # Green
+fi
+
+error() {
+    echo -e "${Red}error${Color_Off}:" "$@" >&2
+    exit 1
+}
+
+success() {
+    echo -e "${Green}$@ ${Color_Off}"
+}
 
 # Storing the timer passed as an argument.
 timer="${1}"
@@ -9,12 +29,12 @@ timer="${1}"
 # Checking if the number of positional parameters ($#) is 0.
 if [[ "$#" == 0 ]]
 then
-	echo "Need an time interval for sleep."
+	error "Need an time interval for sleep."
 	exit 1
 # Checking if the number of positional parameters ($#) are more than 1.
 elif [[ "$#" > 1 ]]
 then
-	echo "Accepts only 1 argument"
+	error "Accepts only 1 argument"
 	exit 1
 # Checking if the $timer is all numbers.
 elif [[ "$timer" =~ ^[0-9]+$ ]]
@@ -43,12 +63,12 @@ then
 		unit="hours"
 	fi
 else
-	echo "Invalid argument, must be a positive integer followed by optional s, m and h for seconds, minutes and hour respectively."
+	error "Invalid argument, must be a positive integer followed by optional s, m and h for seconds, minutes and hour respectively."
 	exit 1
 fi
 
 
-echo Sleeping after $timer $unit
+success Sleeping after $timer $unit
 sleep $seconds && pmset sleepnow
 
 exit 0
