Minor changes

diff --git a/slp b/slp
--- a/slp
+++ b/slp
@@ -8,59 +8,52 @@ Red=''
 Green=''
 
 if [[ -t 1 ]]; then
-    # Reset
-    Color_Off='\033[0m' # Text Reset
+	# Reset
+	Color_Off='\033[0m' # Text Reset
 
-    # Regular Colors
-    Red='\033[0;31m'   # Red
-    Green='\033[0;32m' # Green
+	# Regular Colors
+	Red='\033[0;31m'   # Red
+	Green='\033[0;32m' # Green
 fi
 
 error() {
-    echo -e "${Red}error${Color_Off}:" "$@" >&2
-    exit 1
+	echo -e "${Red}error${Color_Off}:" "$@" >&2
+	exit 1
 }
 
 success() {
-    echo -e "${Green}$@ ${Color_Off}"
+	echo -e "${Green}$@ ${Color_Off}"
 }
 
 # Storing the timer passed as an argument.
 timer="${1}"
 
 # Checking if the number of positional parameters ($#) is 0.
-if [[ "$#" == 0 ]]
-then
+if [[ "$#" == 0 ]]; then
 	error "Need an time interval for sleep."
 	exit 1
 # Checking if the number of positional parameters ($#) are more than 1.
-elif [[ "$#" > 1 ]]
-then
+elif [[ "$#" > 1 ]]; then
 	error "Accepts only 1 argument"
 	exit 1
 # Checking if the $timer is all numbers.
-elif [[ "$timer" =~ ^[0-9]+$ ]]
-then
+elif [[ "$timer" =~ ^[0-9]+$ ]]; then
 	let seconds=$timer
 	unit='seconds'
 # Checking if the $timer has format for units.
-elif [[ "$timer" =~ ^[0-9]+[smh]$ ]]
-then
+elif [[ "$timer" =~ ^[0-9]+[smh]$ ]]; then
 	# Extracting the last character from $timer
 	requnit="${timer:0-1}"
 	# Extracting the string except the last character.
 	timer=${timer%?}
 
-	if [[ "$requnit" == "s" ]]
-	then
+	if [[ "$requnit" == "s" ]]; then
 		let seconds=$timer
 		unit='seconds'
-	elif [[ "$requnit" == "m" ]]
-	then
+	elif [[ "$requnit" == "m" ]]; then
 		let seconds=$timer*60
 		unit='minutes'
-	elif [[ "$requnit" == "h" ]]
-	then
+	elif [[ "$requnit" == "h" ]]; then
 		let seconds=$timer*3600
 		unit="hours"
 	fi
@@ -68,7 +61,6 @@ else
 	error "Invalid argument, must be a positive integer followed by optional s, m and h for seconds, minutes and hour respectively."
 	exit 1
 fi
-
 
 success Sleeping after $timer $unit
 sleep $seconds && pmset sleepnow
